version: "3.7"

services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
  server:
    extends:
      service: builder
    command: [
      "go", "run", "restful_web_app/app.go"
      ]
    environment:
        HTTP_ADDR: 0.0.0.0:1001
    ports:
        - 1001:1001